### ISSUE TITLE
[BUG] index out of range [0] with length 0

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [root4loot/rescope#13]
Running the example in from the readme outputs this:
```
> rescope -u hackerone.com/security -o burpscope.json
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/root4loot/rescope/internal/bbaas/hackerone.Scrape({0xc000014180, 0x16})
        C:/Users/User/go/pkg/mod/github.com/root4loot/rescope@v0.0.0-20221006170311-507297bd1931/internal/bbaas/hackerone/hackerone.go:55 +0x645
github.com/root4loot/rescope/internal/url.BBaas({0xc000050f80?, 0x1?, 0x647408?}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        C:/Users/User/go/pkg/mod/github.com/root4loot/rescope@v0.0.0-20221006170311-507297bd1931/internal/url/url.go:60 +0x4a2
main.main()
        C:/Users/User/go/pkg/mod/github.com/root4loot/rescope@v0.0.0-20221006170311-507297bd1931/main.go:78 +0xcb
```

**Comment by root4loot** [comment]
Same as #12. Fixed temporarily by refreshing tokens. Working on a permanent solution.
